/**
 * Migration 002 — recall schema + all tables + indexes + tsvector triggers
 *
 * Architecture notes:
 *  - Tier 1 tables: user_profiles, google_credentials, availability_rules,
 *    meetings, meeting_guests, meeting_status_history
 *  - Tier 2 tables: notification_channels, pubsub_events, meeting_artifacts,
 *    transcripts, summaries  (always created; only populated when
 *    WORKSPACE_FEATURES_ENABLED=true at runtime)
 *  - No users table — all user_id FKs reference public.users(id) (Notify's table)
 *  - Slot holds are purely in Redis — no DB table
 *
 * IMPORTANT: public.users.id is BIGINT (GENERATED BY DEFAULT AS IDENTITY).
 * All FK columns that reference it use BIGINT, not UUID.
 *
 * Idempotency: every CREATE uses IF NOT EXISTS; triggers use
 * DROP TRIGGER IF EXISTS + CREATE TRIGGER (Postgres has no
 * CREATE TRIGGER IF NOT EXISTS syntax).
 *
 * Safe to run multiple times with no errors.
 */
'use strict';

exports.up = (pgm) => {
  // ── Schema ────────────────────────────────────────────────────────────────
  pgm.sql(`CREATE SCHEMA IF NOT EXISTS recall;`);

  // ── Tier 1 tables ────────────────────────────────────────────────────────

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.user_profiles (
      user_id    BIGINT       PRIMARY KEY REFERENCES public.users(id) ON DELETE RESTRICT,
      google_id  VARCHAR(255) UNIQUE NOT NULL,
      avatar_url TEXT,
      timezone   VARCHAR(64)  DEFAULT 'UTC',
      created_at TIMESTAMPTZ  DEFAULT now(),
      updated_at TIMESTAMPTZ  DEFAULT now()
    );
  `);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.google_credentials (
      id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id                 BIGINT      UNIQUE NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
      refresh_token_encrypted TEXT        NOT NULL,
      access_token_encrypted  TEXT,
      token_expiry            TIMESTAMPTZ,
      scopes                  TEXT[],
      created_at              TIMESTAMPTZ DEFAULT now(),
      updated_at              TIMESTAMPTZ DEFAULT now()
    );
  `);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.availability_rules (
      id          UUID     PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id     BIGINT   NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
      day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
      start_time  TIME     NOT NULL,
      end_time    TIME     NOT NULL,
      created_at  TIMESTAMPTZ DEFAULT now()
    );
  `);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.meetings (
      id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
      organizer_id        BIGINT       NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
      google_event_id     VARCHAR(255) NOT NULL,
      google_calendar_id  VARCHAR(255) NOT NULL,
      recurring_event_id  VARCHAR(255),
      rrule               TEXT,
      is_recurring        BOOLEAN      DEFAULT false,
      title               VARCHAR(500) NOT NULL,
      description         TEXT,
      start_time          TIMESTAMPTZ  NOT NULL,
      end_time            TIMESTAMPTZ  NOT NULL,
      timezone            VARCHAR(64)  NOT NULL,
      meet_link           TEXT,
      meet_space_id       VARCHAR(255),
      status              VARCHAR(20)  NOT NULL DEFAULT 'scheduled',
      created_at          TIMESTAMPTZ  DEFAULT now(),
      updated_at          TIMESTAMPTZ  DEFAULT now(),
      UNIQUE(google_event_id, google_calendar_id)
    );
  `);

  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_meetings_organizer   ON recall.meetings(organizer_id);`);
  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_meetings_time_range  ON recall.meetings(start_time, end_time);`);
  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_meetings_status      ON recall.meetings(status);`);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.meeting_guests (
      id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
      meeting_id      UUID         NOT NULL REFERENCES recall.meetings(id) ON DELETE CASCADE,
      email           VARCHAR(255) NOT NULL,
      name            VARCHAR(255),
      response_status VARCHAR(20)  DEFAULT 'needsAction'
    );
  `);

  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_meeting_guests_meeting ON recall.meeting_guests(meeting_id);`);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.meeting_status_history (
      id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
      meeting_id  UUID        NOT NULL REFERENCES recall.meetings(id) ON DELETE CASCADE,
      from_status VARCHAR(20),
      to_status   VARCHAR(20) NOT NULL,
      reason      TEXT,
      changed_at  TIMESTAMPTZ DEFAULT now()
    );
  `);

  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_status_history_meeting ON recall.meeting_status_history(meeting_id);`);

  // ── Tier 2 tables (always created; populated only when Workspace is enabled) ─

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.notification_channels (
      id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id       BIGINT       NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
      channel_id    VARCHAR(255) NOT NULL,
      resource_id   VARCHAR(255),
      resource_type VARCHAR(50),
      expiration    TIMESTAMPTZ,
      created_at    TIMESTAMPTZ  DEFAULT now()
    );
  `);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.pubsub_events (
      id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
      message_id    VARCHAR(255) UNIQUE NOT NULL,
      event_type    VARCHAR(100),
      resource_name TEXT,
      payload       JSONB,
      status        VARCHAR(20)  DEFAULT 'received',
      error_message TEXT,
      received_at   TIMESTAMPTZ  DEFAULT now(),
      processed_at  TIMESTAMPTZ
    );
  `);

  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_pubsub_events_status ON recall.pubsub_events(status);`);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.meeting_artifacts (
      id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
      meeting_id           UUID        REFERENCES recall.meetings(id) ON DELETE CASCADE,
      conference_record_id VARCHAR(255),
      type                 VARCHAR(20) NOT NULL,
      drive_file_id        VARCHAR(255),
      docs_file_id         VARCHAR(255),
      status               VARCHAR(20) DEFAULT 'pending',
      fetched_at           TIMESTAMPTZ,
      created_at           TIMESTAMPTZ DEFAULT now()
    );
  `);

  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_artifacts_meeting ON recall.meeting_artifacts(meeting_id);`);
  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_artifacts_status  ON recall.meeting_artifacts(status);`);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.transcripts (
      id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
      meeting_id    UUID        NOT NULL REFERENCES recall.meetings(id) ON DELETE CASCADE,
      artifact_id   UUID        REFERENCES recall.meeting_artifacts(id),
      content       TEXT        NOT NULL,
      search_vector tsvector,
      created_at    TIMESTAMPTZ DEFAULT now()
    );
  `);

  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_transcript_search ON recall.transcripts USING GIN(search_vector);`);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.summaries (
      id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
      meeting_id    UUID        NOT NULL REFERENCES recall.meetings(id) ON DELETE CASCADE,
      artifact_id   UUID        REFERENCES recall.meeting_artifacts(id),
      content       TEXT        NOT NULL,
      source        VARCHAR(30) DEFAULT 'gemini_native',
      search_vector tsvector,
      created_at    TIMESTAMPTZ DEFAULT now()
    );
  `);

  pgm.sql(`CREATE INDEX IF NOT EXISTS idx_summary_search ON recall.summaries USING GIN(search_vector);`);

  // ── tsvector update triggers ──────────────────────────────────────────────
  // Postgres does not support CREATE TRIGGER IF NOT EXISTS, so we use
  // DROP TRIGGER IF EXISTS + CREATE TRIGGER — this is safe and idempotent.

  pgm.sql(`
    DROP TRIGGER IF EXISTS tsvector_update_transcripts ON recall.transcripts;
    CREATE TRIGGER tsvector_update_transcripts
      BEFORE INSERT OR UPDATE ON recall.transcripts
      FOR EACH ROW
      EXECUTE FUNCTION tsvector_update_trigger(
        search_vector, 'pg_catalog.english', content
      );
  `);

  pgm.sql(`
    DROP TRIGGER IF EXISTS tsvector_update_summaries ON recall.summaries;
    CREATE TRIGGER tsvector_update_summaries
      BEFORE INSERT OR UPDATE ON recall.summaries
      FOR EACH ROW
      EXECUTE FUNCTION tsvector_update_trigger(
        search_vector, 'pg_catalog.english', content
      );
  `);
};

exports.down = (pgm) => {
  pgm.sql(`DROP TRIGGER IF EXISTS tsvector_update_summaries    ON recall.summaries;`);
  pgm.sql(`DROP TRIGGER IF EXISTS tsvector_update_transcripts  ON recall.transcripts;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.summaries              CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.transcripts            CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.meeting_artifacts      CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.pubsub_events          CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.notification_channels  CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.meeting_status_history CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.meeting_guests         CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.meetings               CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.availability_rules     CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.google_credentials     CASCADE;`);
  pgm.sql(`DROP TABLE IF EXISTS recall.user_profiles          CASCADE;`);
  pgm.sql(`DROP SCHEMA IF EXISTS recall CASCADE;`);
};
