/**
 * Migration 003 — Own userbase: recall.users + retarget FKs
 *
 * For databases that already applied migration 002 when FKs pointed at
 * public.users: create recall.users (if missing) and point existing FKs at it.
 *
 * Fresh installs that run an updated 002 already have recall.users and
 * recall.users FKs; this migration is then a no-op (IF NOT EXISTS / DROP+ADD).
 *
 * If you dropped recall.* tables but left pgmigrations intact, reset those
 * migration rows (or DROP SCHEMA recall CASCADE and truncate pgmigrations)
 * so 001+002 recreate the full schema — this file does not recreate every table.
 */
'use strict';

exports.up = (pgm) => {
  pgm.sql(`CREATE SCHEMA IF NOT EXISTS recall;`);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS recall.users (
      id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email      VARCHAR(255) NOT NULL UNIQUE,
      username   VARCHAR(255) NOT NULL,
      role       VARCHAR(255) NOT NULL DEFAULT 'CLIENT',
      created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
    );
  `);

  pgm.sql(`
    DO $$
    BEGIN
      IF to_regclass('recall.user_profiles') IS NOT NULL THEN
        ALTER TABLE recall.user_profiles DROP CONSTRAINT IF EXISTS user_profiles_user_id_fkey;
        ALTER TABLE recall.user_profiles
          ADD CONSTRAINT user_profiles_user_id_fkey
          FOREIGN KEY (user_id) REFERENCES recall.users(id) ON DELETE RESTRICT;
      END IF;

      IF to_regclass('recall.google_credentials') IS NOT NULL THEN
        ALTER TABLE recall.google_credentials DROP CONSTRAINT IF EXISTS google_credentials_user_id_fkey;
        ALTER TABLE recall.google_credentials
          ADD CONSTRAINT google_credentials_user_id_fkey
          FOREIGN KEY (user_id) REFERENCES recall.users(id) ON DELETE RESTRICT;
      END IF;

      IF to_regclass('recall.availability_rules') IS NOT NULL THEN
        ALTER TABLE recall.availability_rules DROP CONSTRAINT IF EXISTS availability_rules_user_id_fkey;
        ALTER TABLE recall.availability_rules
          ADD CONSTRAINT availability_rules_user_id_fkey
          FOREIGN KEY (user_id) REFERENCES recall.users(id) ON DELETE RESTRICT;
      END IF;

      IF to_regclass('recall.meetings') IS NOT NULL THEN
        ALTER TABLE recall.meetings DROP CONSTRAINT IF EXISTS meetings_organizer_id_fkey;
        ALTER TABLE recall.meetings
          ADD CONSTRAINT meetings_organizer_id_fkey
          FOREIGN KEY (organizer_id) REFERENCES recall.users(id) ON DELETE RESTRICT;
      END IF;

      IF to_regclass('recall.notification_channels') IS NOT NULL THEN
        ALTER TABLE recall.notification_channels DROP CONSTRAINT IF EXISTS notification_channels_user_id_fkey;
        ALTER TABLE recall.notification_channels
          ADD CONSTRAINT notification_channels_user_id_fkey
          FOREIGN KEY (user_id) REFERENCES recall.users(id) ON DELETE RESTRICT;
      END IF;
    END $$;
  `);
};

exports.down = (pgm) => {
  // Cannot restore public.users FKs — Recall no longer depends on that table.
  pgm.sql(`
    ALTER TABLE IF EXISTS recall.notification_channels DROP CONSTRAINT IF EXISTS notification_channels_user_id_fkey;
    ALTER TABLE IF EXISTS recall.meetings               DROP CONSTRAINT IF EXISTS meetings_organizer_id_fkey;
    ALTER TABLE IF EXISTS recall.availability_rules     DROP CONSTRAINT IF EXISTS availability_rules_user_id_fkey;
    ALTER TABLE IF EXISTS recall.google_credentials     DROP CONSTRAINT IF EXISTS google_credentials_user_id_fkey;
    ALTER TABLE IF EXISTS recall.user_profiles          DROP CONSTRAINT IF EXISTS user_profiles_user_id_fkey;
    DROP TABLE IF EXISTS recall.users CASCADE;
  `);
};
